//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testdb
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class bctc
    {
        public string mack { get; set; }
        public int doanhthuthuan { get; set; }
        public int giavon { get; set; }
        public int phiquanly { get; set; }
        public int loinhuantruocthue { get; set; }
        public int loinhuansauthue { get; set; }
        public int loinhuankhac { get; set; }
        public int quy { get; set; }
        public int nam { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; set; }
    }
}
