//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testdb
{
    using System;
    using System.Collections.Generic;
    
    public partial class congty
    {
        public string mack { get; set; }
        public string tencty { get; set; }
        public string nhomnganh { get; set; }
        public int socp { get; set; }
    }
}
